### ISSUE TITLE
Add screenshot

### ISSUE THREAD

**Issue by DamienCassou** [tarsius/backline#1]
You might want to add a before/after screenshot to illustrate the README.

**Comment by alphapapa** [comment]
This will be especially great when it supports org-mode!  :)  Thanks, Jonas!

**Comment by tarsius** [comment]
> You might want to add a before/after screenshot to illustrate the README.

Done.

> This will be especially great when it supports org-mode! :)

There's a TODO in the source for that and this issue isn't about that ;-)
