### ISSUE TITLE
add support for orgmode

### ISSUE THREAD

**Issue by bibekpokharel** [tarsius/backline#2]
I have been interested in having a similar feature for org-mode. Do you plan to extend this to orgmode / do you have an idea on how it can be done? I installed your package and tried it with orgmode but it did not work as intended.

**Comment by tarsius** [comment]
Yes. The only function defined by this package looks like this:

```elisp
(defun backline-update (from to _hide)
  "When hidings, add an overlay to extend header's appearance to window edge."
  ;; TODO Also support `outline-mode' and `org-mode'.
  (when outline-minor-mode
    ...)
```

You probably can do

```diff
-  (when outline-minor-mode
+  (progn
```

and it might just work. Possibly with minor bugs. Or none. Or major ones.

I don't know exactly why I haven't done that. All I can say with certainty is that I was not certain that doing that would have been the right call at the time I made another call.

Eventually I will look at this again and make up my mind about it.

**Comment by tarsius** [comment]
A broken implementation can be found in the `org-mode` branch.
